name: Build winecx

on:
  workflow_dispatch:
    inputs:
      version:
        description: CrossOver source version
        required: true

jobs:
  build:
    runs-on: macos-15-intel
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          brew update
          brew install bison ccache gettext mingw-w64 pkgconfig
          brew install freetype gnutls libpcap sdl2

      - uses: hendrikmuhs/ccache-action@v1
        with:
          key: winecx-${{ inputs.version }}

      - name: Build wine
        run: ./scripts/build-wine.sh "${{ inputs.version }}"

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ inputs.version }}
          name: winecx ${{ inputs.version }}
          files: winecx-${{ inputs.version }}-osx64.tar.gz
          fail_on_unmatched_files: true
